INSERT INTO equipo (nombre, liga, pais) VALUES ('Real Madrid', 'La Liga', 'España');
INSERT INTO equipo (nombre, liga, pais) VALUES ('FC Barcelona', 'La Liga', 'España');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Manchester United', 'Premier League', 'Inglaterra');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Liverpool FC', 'Premier League', 'Inglaterra');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Bayern Munich', 'Bundesliga', 'Alemania');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Borussia Dortmund', 'Bundesliga', 'Alemania');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Paris Saint-Germain', 'Ligue 1', 'Francia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Olympique Lyon', 'Ligue 1', 'Francia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Juventus', 'Serie A', 'Italia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('AC Milan', 'Serie A', 'Italia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Ajax Amsterdam', 'Eredivisie', 'Países Bajos');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Atlético Madrid', 'La Liga', 'España');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Chelsea FC', 'Premier League', 'Inglaterra');
INSERT INTO equipo (nombre, liga, pais) VALUES ('RB Leipzig', 'Bundesliga', 'Alemania');
INSERT INTO equipo (nombre, liga, pais) VALUES ('AS Monaco', 'Ligue 1', 'Francia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Inter Milan', 'Serie A', 'Italia');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Valencia CF', 'La Liga', 'España');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Tottenham Hotspur', 'Premier League', 'Inglaterra');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Bayer Leverkusen', 'Bundesliga', 'Alemania');
INSERT INTO equipo (nombre, liga, pais) VALUES ('Marseille OM', 'Ligue 1', 'Francia');